### ISSUE TITLE
Panic for version parsing after upgrade to v0.0.9

### ISSUE THREAD

**Issue by steve-fraser** [kube-vip/kube-vip-cloud-provider#94]
```
panic: version string "" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"

goroutine 1 [running]:
k8s.io/component-base/metrics.parseVersion({{0x0, 0x0}, {0x0, 0x0}, {0x1f44b17, 0x0}, {0x1c97daf, 0xb}, {0x0, 0x0}, ...})
        /go/pkg/mod/k8s.io/component-base@v0.25.4/metrics/version_parser.go:47 +0x274
k8s.io/component-base/metrics.newKubeRegistry({{0x0, 0x0}, {0x0, 0x0}, {0x1f44b17, 0x0}, {0x1c97daf, 0xb}, {0x0, 0x0}, ...})
        /go/pkg/mod/k8s.io/component-base@v0.25.4/metrics/registry.go:320 +0x119
k8s.io/component-base/metrics.NewKubeRegistry()
        /go/pkg/mod/k8s.io/component-base@v0.25.4/metrics/registry.go:335 +0x78
k8s.io/component-base/metrics/legacyregistry.init()
        /go/pkg/mod/k8s.io/component-base@v0.25.4/metrics/legacyregistry/registry.go:29 +0x1d
```

**Comment by lubronzhan** [comment]
Same as this one https://github.com/kube-vip/kube-vip-cloud-provider/issues/95
Because of missing version variable in release job. 
Working on it now

**Comment by lubronzhan** [comment]
Now it's fixed please try again with newest image
